#import <TargetConditionals.h>
#if TARGET_OS_OSX
/*!
 @file       BEPathControl.m
 @abstract   Implementation of BEPathControl, an NSPathControl subclass that limits displayed path items based on a relative URL.
 @discussion This file contains the implementation for the @c BEPathControl class.
			 It overrides the standard @c setURL: and implements the @c relativeURL
			 property to enable the trimming of path components. The core logic is
			 contained in @c rebuildRelativeItems:, which filters the absolute
			 path items generated by the superclass using the @c containsURL: method.
			 
			 This ensures that only file path components descendant from the
			 @c relativeURL are shown in the path control.
 @copyright  -© 2025 Delicense - @belisoful. All rights released.
 @date       2025-11-03
 @author     belisoful@icloud.com
 */

#import "BEPathControl.h"

NS_ASSUME_NONNULL_BEGIN


@implementation BEPathControl

#pragma mark - Property Overrides

/*!
 @method     setURL:
 @abstract   Sets the path control's main URL and triggers the path trimming logic.
 @param      url The full absolute URL to display in the path control.
 @discussion This method overrides the standard @c NSPathControl implementation.
			 It first standardizes the URL for consistency and then calls
			 @c rebuildRelativeItems: to generate and filter the path items
			 based on the current @c relativeURL.
 */
- (void)setURL:(nullable NSURL *)url {
	if (url) {
		url = url.standardizedURL;
		[self rebuildRelativeItems:url];
	} else {
		[super setURL:nil];
	}
}

/*!
 @method     setRelativeURL:
 @abstract   Sets the relative root URL for the path control.
 @param      relativeURL The new relative root URL.
 @discussion This setter updates the internal @c _relativeURL instance variable,
			 standardizes the URL, and then calls @c rebuildRelativeItems: with
			 a @c nil URL argument to re-evaluate the currently displayed path
			 against the new relative root.
 */
- (void)setRelativeURL:(nullable NSURL *)relativeURL {
	_relativeURL = relativeURL.standardizedURL;
	[self rebuildRelativeItems:_relativeURL ? nil : self.URL];
}

#pragma mark - Path Trimming

/*!
 @method     rebuildRelativeItems:
 @abstract   Filters the path control's items to only show components relative to the relative URL.
 @param      url The new absolute URL to set, or @c nil to re-use the existing one.
 @discussion This is the core logic for path trimming.
			 
			 1. **Update Base URL**: If a non-nil @c url is provided, it calls
				the superclass's @c setURL: to update the base path and automatically
				generate the full set of path items.
			 2. **Check Relative URL**: If @c _relativeURL is nil, the method exits,
				leaving the full path (standard @c NSPathControl behavior).
			 3. **Ensure Items**: If the input @c url was nil, it calls the superclass's
				@c setURL: with the existing @c self.URL to force the regeneration of
				path items, ensuring @c super.pathItems is up to date.
			 4. **Filter**: It iterates through the auto-generated absolute path items
				(@c super.pathItems) and removes any item whose URL is not a descendant
				of the @c relativeURL (using @c containsURL:).
			 5. **Apply Filtered Items**: The filtered array is set back to @c super.pathItems,
				which updates the display.
 */
- (void)rebuildRelativeItems:(nullable NSURL *)url {
	
	if (url) {
		[super setURL:url];
	}
	
	if (!_relativeURL) {
		   return; // Nothing to trim
	}
	
	if (!url) {
		[super setURL:self.URL];
	}
	
	NSArray<NSPathControlItem*> *items = super.pathItems;  // The auto-generated absolute items

	// Keep only the items at or below relativeURL.
	NSMutableArray<NSPathControlItem*> *newPathItems = [NSMutableArray arrayWithCapacity:items.count];
	for(NSPathControlItem *cell in items) {
		if ([self containsURL:cell.URL]) {
			[newPathItems addObject:cell];
		}
	}

	super.pathItems = newPathItems.copy;
}

#pragma mark - Path Comparison

/*!
 @method     containsURL:
 @abstract   Determines if a given URL is at, or below, the relative URL.
 @param      checkUrl The URL to check for containment. May be @c nil.
 @discussion Comparison is performed on standardized path components, not on raw
			 absolute strings. @c relativeURL is contained iff its component sequence is a
			 prefix of @c checkUrl's component sequence. This is exact at directory
			 boundaries and therefore avoids the classic string-prefix pitfalls:
			 @c /a/Projects does NOT match @c /a/ProjectsX, files are not mistaken for
			 directories, and percent-encoding differences are normalized away (path
			 components are decoded).

			 The check passes if:
			 - @c relativeURL is @c nil (no restriction), or
			 - @c checkUrl equals @c relativeURL, or
			 - @c checkUrl is a descendant of @c relativeURL.

			 Note: standardization resolves @c . and @c .. and redundant slashes but does
			 NOT resolve symlinks. If you require symlink-insensitive matching, pass URLs
			 that have already been resolved with @c -URLByResolvingSymlinksInPath.
 @return     @c YES if @c checkUrl is within the hierarchy rooted at @c relativeURL.
 */
- (BOOL)containsURL:(nullable NSURL*)checkUrl {
	NSURL *relativeURL = self.relativeURL;
	if (!relativeURL) {
		return YES; // No restriction
	}
	if (!checkUrl) {
		return NO;
	}

	// Require matching schemes (e.g. don't let an http URL match a file root) before
	// comparing path components.
	NSString *baseScheme = relativeURL.scheme;
	NSString *candidateScheme = checkUrl.scheme;
	if (baseScheme || candidateScheme) {
		if (![baseScheme isEqualToString:candidateScheme]) {
			return NO;
		}
	}

	NSArray<NSString *> *base = relativeURL.standardizedURL.pathComponents;
	NSArray<NSString *> *candidate = checkUrl.standardizedURL.pathComponents;

	if (candidate.count < base.count) {
		return NO;
	}
	for (NSUInteger i = 0; i < base.count; i++) {
		if (![base[i] isEqualToString:candidate[i]]) {
			return NO;
		}
	}
	return YES;
}

@end

NS_ASSUME_NONNULL_END
#endif // TARGET_OS_OSX
